### ISSUE TITLE
Can't diagnose the cause, but since yesterday, every generated SVG has the wrong viewbox coordinates

### ISSUE THREAD

**Issue by Applethal** [kisonecat/tikzjax#27]
![image](https://github.com/kisonecat/tikzjax/assets/114657050/9dd08c76-15b0-4a57-9af7-9bcec34a97e6)

This is true for every big tikz figure, I tested with small ones and apparently they are correctly framed. This wasn't the case prior to the making of this post.

**Comment by kisonecat** [comment]
I made an update yesterday to add support for additional TikZ packages which presumably broke this.

This is a site that is using the version on `tikzjax.com` ?

**Comment by Applethal** [comment]
> I made an update yesterday to add support for additional TikZ packages which presumably broke this.
> 
> This is a site that is using the version on `tikzjax.com` ?

Thanks for clarifications. Yes I am using the actual version. 
notable examples:
https://www.applethal.com/recommendations/recipes/pasta_onions
https://www.applethal.com/recommendations/recipes/ricethunfish/
https://www.applethal.com/sandbox/scheduling/
https://www.applethal.com/blog/divided_by_zero_2/

I am using no extra packages, just vanilla Tikz btw.

**Comment by kisonecat** [comment]
I think I have a fix: https://github.com/kisonecat/dvi2html/commit/b97a579444fea0494f2439d9748435a128bd1713 adds a `<g transform>` to every `<svg>`.  Let me know if this repairs the regression.

**Comment by Applethal** [comment]
Hello, yes it worked!

**Comment by kisonecat** [comment]
Great!  I'm glad to hear it.
